#Jekyll config
theme: jekyll-theme-minimal

title: Charles James Sayers
description: Electronic structure and dynamics of 2D materials
logo: /images/VSe2_geo_large.png

show_downloads: false
#google_analytics: UA-149329790-2

markdown: kramdown
highlighter: rouge
