#Jekyll config
theme: jekyll-theme-minimal

title: C. J. Sayers
description: Investigating the electronic structure and dynamics of 2D materials.
logo: /images/tise2_-0p8_crop.png

show_downloads: false
google_analytics: UA-149329790-2

markdown: kramdown
highlighter: rouge

url: "https://cjsayers.github.io"
plugins:
  - jekyll-sitemap
